CREATE TABLE [dbo].[tblProfile]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] VARCHAR(25) NOT NULL,
	[LobbyId] UNIQUEIDENTIFIER NOT NULL,
	[HelmId] INT NOT NULL,
	[ArmorId] INT NOT NULL,
	[ColorId] INT NOT NULL
)
